name: Demo Workflow
on:
  push:
    branches:
      - main

permissions:
  contents: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: |
          mvn -B package --file pom.xml
          ls -l target/
      - name: Upload JAR file
        uses: actions/upload-artifact@v4
        with:
          name: DemoGithubActions
          path: ./target/

  sonarqube:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure full history is fetched for SonarQube analysis

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: DemoGithubActions # Ensure the artifact name matches the upload step
          path: ./target/

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5 
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Required for SonarQube to access GitHub
        with:
          projectBaseDir: ./target/
          args: >
            -Dsonar.organization=${{ vars.SONAR_ORG }}
            -Dsonar.projectKey=${{ vars.SONAR_PROJECT_KEY }}
            -Dsonar.projectVersion=${{ vars.PROJECT_VERSION }}
            -Dsonar.java.binaries=target/classes
            -Dsonar.verbose=false 
            -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
            

  docker-build:
    runs-on: ubuntu-latest
    needs: sonarqube
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: DemoGithubActions
          path: ./target/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU (for multi-platform support)
        uses: docker/setup-qemu-action@v3     

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: joehaddy/spring-boot-app:latest
        