name: Demo Workflow
on:
  push:
    branches:
      - main

permissions:
  contents: read
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: |
          mvn -B package --file pom.xml
          ls -l target/
      - name: Upload JAR file
        uses: actions/upload-artifact@v4
        with:
          name: DemoGithubActions
          path: ./target/

  sonarqube:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensure full history is fetched for SonarQube analysis

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: DemoGithubActions # Ensure the artifact name matches the upload step
          path: ./target/

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5

      - name: Build & Analyze with Maven
        run: |
         mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
         -Dsonar.organization=your-sonar-org \
         -Dsonar.projectKey=your-sonar-project-key \
         -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
         -Dsonar.login=${{ secrets.SONAR_TOKEN }}


            

  docker-build:
    runs-on: ubuntu-latest
    needs: sonarqube
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: DemoGithubActions
          path: ./target/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU (for multi-platform support)
        uses: docker/setup-qemu-action@v3     

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: joehaddy/spring-boot-app:latest
        