name: Demo Workflow
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          cache-dependency-path: 'DemoGithubActions/pom.xml' # optional

      - name: Build with Maven
        run: |
            mvn -B package --file pom.xml
            ls -l DemoGithubActions/target
        